/**
 * Anthony’s curated Switch → Switch 2 Zelda progression data.
 * localStorage key: zelda-progression-v1
 */
window.ZELDA_DATA = {
  storageKey: "zelda-progression-v1",

  phases: [
    {
      id: "phase-1",
      title: "Phase 1 — Now on Switch",
      subtitle: "Foundations you can play today on Switch / NSO",
      gameIds: ["alttp", "minish", "skyward"],
    },
    {
      id: "phase-2",
      title: "Phase 2 — Switch 2",
      subtitle: "The main path once Switch 2 libraries unlock",
      gameIds: [
        "links-awakening",
        "oot",
        "majora",
        "wind-waker",
        "twilight",
        "botw",
        "totk",
      ],
    },
  ],

  optionalSection: {
    id: "optional",
    title: "Later / Optional",
    subtitle: "Worth knowing — not required for the hero path",
    gameIds: [
      "oracle-ages",
      "oracle-seasons",
      "eow",
      "zelda1",
      "zelda2",
      "four-swords",
      "fsa",
      "tfh",
      "ph",
      "st",
      "albw",
    ],
  },

  games: {
    alttp: {
      id: "alttp",
      order: 1,
      title: "A Link to the Past",
      shortTitle: "ALttP",
      platform: "SNES NSO",
      importance: "play",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/2/21/The_Legend_of_Zelda_A_Link_to_the_Past_SNES_Game_Cover.jpg",
      alt: "North American box art for The Legend of Zelda: A Link to the Past",
      versionNote: "SNES via Nintendo Switch Online",
      why: "Foundational 2D Zelda — the template for dungeons, items, and the Light/Dark World dual map. Best place to start the Switch path.",
      chronology: "Downfall branch classic",
    },
    minish: {
      id: "minish",
      order: 2,
      title: "The Minish Cap",
      shortTitle: "Minish Cap",
      platform: "GBA NSO+",
      importance: "recommended",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/0/0a/TLOZ-_Minish_Cap_NA_Box_art.png",
      alt: "North American box art for The Legend of Zelda: The Minish Cap",
      versionNote: "Game Boy Advance — NSO Expansion Pack",
      why: "Recommended optional. Charming origin for the Four Sword lore and a polished top-down adventure between ALttP and Skyward.",
      chronology: "Force Era — Four Sword origin",
    },
    skyward: {
      id: "skyward",
      order: 3,
      title: "Skyward Sword HD",
      shortTitle: "Skyward Sword",
      platform: "Switch",
      importance: "essential-ish",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/9/99/Legend_of_Zelda_Skyward_Sword_boxart.png",
      alt: "Box art for The Legend of Zelda: Skyward Sword",
      versionNote: "Skyward Sword HD (Switch)",
      why: "Essential-ish origin mythology — Demise, the Master Sword’s forging, and the sky-island setup that echoes through the series.",
      chronology: "Earliest official timeline entry",
    },
    "links-awakening": {
      id: "links-awakening",
      order: 4,
      title: "Link’s Awakening",
      shortTitle: "Link’s Awakening",
      platform: "Switch 2 enhanced",
      importance: "play",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/c/c1/Link%27s_Awakening.png",
      alt: "Box art for The Legend of Zelda: Link's Awakening (Switch remake)",
      versionNote: "2019 remake — Switch 2 enhanced version",
      why: "Self-contained dream-island classic. Perfect palate cleanser and a must-play remake before diving into the 3D era.",
      chronology: "Downfall branch — after ALttP",
    },
    oot: {
      id: "oot",
      order: 5,
      title: "Ocarina of Time",
      shortTitle: "OoT",
      platform: "Switch 2 remake",
      importance: "essential",
      statusDefault: "todo",
      waitBadge: true,
      waitLabel: "WAIT — Nov 5, 2026",
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/5/57/The_Legend_of_Zelda_Ocarina_of_Time.jpg",
      alt: "Box art for The Legend of Zelda: Ocarina of Time",
      versionNote: "Ocarina of Time Switch 2 remake (announced Nov 5, 2026)",
      why: "Essential. The hub of the official chronology — Child / Adult / Downfall branches all split from here. Wait for the Switch 2 remake.",
      chronology: "Timeline nexus",
    },
    majora: {
      id: "majora",
      order: 6,
      title: "Majora’s Mask",
      shortTitle: "Majora’s Mask",
      platform: "N64 Classics Switch 2",
      importance: "play",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/6/60/The_Legend_of_Zelda_-_Majora%27s_Mask_Box_Art.jpg",
      alt: "Box art for The Legend of Zelda: Majora's Mask",
      versionNote: "N64 Classics on Switch 2 (after OoT)",
      why: "Direct sequel to OoT on the Child timeline. Dense, emotional, and one of the series’ creative peaks — play right after OoT.",
      chronology: "Child timeline — sequel to OoT",
    },
    "wind-waker": {
      id: "wind-waker",
      order: 7,
      title: "The Wind Waker",
      shortTitle: "Wind Waker",
      platform: "GameCube Classics Switch 2",
      importance: "essential",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/7/79/The_Legend_of_Zelda_The_Wind_Waker.jpg",
      alt: "Box art for The Legend of Zelda: The Wind Waker",
      versionNote: "GameCube Classics on Switch 2",
      why: "Essential Adult-timeline ocean adventure. Cel-shaded masterpiece that answers what happened after OoT’s Adult ending.",
      chronology: "Adult timeline",
    },
    twilight: {
      id: "twilight",
      order: 8,
      title: "Twilight Princess",
      shortTitle: "Twilight Princess",
      platform: "Waiting for Switch",
      importance: "essential",
      statusDefault: "todo",
      waitBadge: true,
      waitLabel: "BLOCKED — no Switch release yet",
      blocked: true,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/0/0e/The_Legend_of_Zelda_Twilight_Princess_Game_Cover.jpg",
      alt: "Box art for The Legend of Zelda: Twilight Princess",
      versionNote: "No native Switch / Switch 2 release yet — watch Classics / remaster news",
      why: "Essential but blocked. Child-timeline epic with Midna and the Twilight Realm. Hold a slot until Nintendo brings it over.",
      chronology: "Child timeline — after Majora",
    },
    botw: {
      id: "botw",
      order: 9,
      title: "Breath of the Wild",
      shortTitle: "BotW",
      platform: "Switch 2 Edition",
      importance: "essential",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/c/c6/The_Legend_of_Zelda_Breath_of_the_Wild.jpg",
      alt: "Box art for The Legend of Zelda: Breath of the Wild",
      versionNote: "Breath of the Wild — Nintendo Switch 2 Edition",
      why: "Essential open-air reinvention. Play the Switch 2 Edition for performance and quality-of-life, then go straight into TotK.",
      chronology: "Far future — after all classic branches",
    },
    totk: {
      id: "totk",
      order: 10,
      title: "Tears of the Kingdom",
      shortTitle: "TotK",
      platform: "Switch 2 Edition",
      importance: "essential",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/f/fb/The_Legend_of_Zelda_Tears_of_the_Kingdom_cover.jpg",
      alt: "Box art for The Legend of Zelda: Tears of the Kingdom",
      versionNote: "Tears of the Kingdom — Nintendo Switch 2 Edition",
      why: "Essential direct sequel to BotW. Play immediately after Breath of the Wild — story, systems, and world are continuous.",
      chronology: "Direct sequel to BotW",
    },

    /* —— Later / optional —— */
    "oracle-ages": {
      id: "oracle-ages",
      order: 20,
      title: "Oracle of Ages",
      shortTitle: "Oracle Ages",
      platform: "GBC (NSO+)",
      importance: "optional",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/4/47/The_Legend_of_Zelda_Oracle_of_Seasons_and_Oracle_of_Ages_Game_Cover.png",
      alt: "Combined box art for Oracle of Ages and Oracle of Seasons",
      versionNote: "Game Boy Color — linked with Seasons",
      why: "Optional+. Clever time-travel paired game with Oracle of Seasons. Great if you want more 2D after ALttP.",
      chronology: "Downfall branch",
    },
    "oracle-seasons": {
      id: "oracle-seasons",
      order: 21,
      title: "Oracle of Seasons",
      shortTitle: "Oracle Seasons",
      platform: "GBC (NSO+)",
      importance: "optional",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/4/47/The_Legend_of_Zelda_Oracle_of_Seasons_and_Oracle_of_Ages_Game_Cover.png",
      alt: "Combined box art for Oracle of Ages and Oracle of Seasons",
      versionNote: "Game Boy Color — linked with Ages",
      why: "Optional+. Season-shifting counterpart to Ages. Play as a pair for the linked ending.",
      chronology: "Downfall branch",
    },
    eow: {
      id: "eow",
      order: 22,
      title: "Echoes of Wisdom",
      shortTitle: "Echoes of Wisdom",
      platform: "Switch",
      importance: "recommended",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/1/1e/The_Legend_of_Zelda_%E2%80%93_Echoes_of_Wisdom.jpg",
      alt: "Box art for The Legend of Zelda: Echoes of Wisdom",
      versionNote: "Nintendo Switch (2024)",
      why: "Recommended. Zelda as the protagonist with echo-building puzzles — fresh systems that sit nicely beside the hero path.",
      chronology: "Downfall-adjacent / soft reboot vibes",
    },
    zelda1: {
      id: "zelda1",
      order: 23,
      title: "The Legend of Zelda",
      shortTitle: "Zelda I",
      platform: "NES NSO",
      importance: "optional",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Zelda_2017.svg/960px-Zelda_2017.svg.png",
      alt: "The Legend of Zelda series logo",
      versionNote: "NES via NSO",
      why: "Optional historical curiosity. The original open overworld — rough by modern standards but iconic.",
      chronology: "Downfall — late era",
    },
    zelda2: {
      id: "zelda2",
      order: 24,
      title: "Zelda II: The Adventure of Link",
      shortTitle: "Zelda II",
      platform: "NES NSO",
      importance: "skip",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/f/fd/Zelda_II_The_Adventure_of_Link_box.jpg",
      alt: "Box art for Zelda II: The Adventure of Link",
      versionNote: "NES via NSO",
      why: "Skip for this path. Side-scrolling RPG experiment — historically important, but not required for series feel.",
      chronology: "Downfall — after Zelda I",
    },
    "four-swords": {
      id: "four-swords",
      order: 25,
      title: "Four Swords",
      shortTitle: "Four Swords",
      platform: "Various",
      importance: "skip",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover: null,
      alt: "Placeholder for Four Swords",
      versionNote: "Multiplayer-focused",
      why: "Skip. Designed around multiplayer; not central to a single-player Switch → Switch 2 path.",
      chronology: "Force Era",
    },
    fsa: {
      id: "fsa",
      order: 26,
      title: "Four Swords Adventures",
      shortTitle: "FSA",
      platform: "GameCube",
      importance: "skip",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/5/56/The_Legend_of_Zelda_Four_Swords_Adventures_Game_Cover.jpg",
      alt: "Box art for Four Swords Adventures",
      versionNote: "GameCube — no Switch release",
      why: "Skip. Multiplayer/GameCube-centric; Vaati/Ganon lore is covered enough via Minish Cap.",
      chronology: "Force Era / Child adjacent",
    },
    tfh: {
      id: "tfh",
      order: 27,
      title: "Tri Force Heroes",
      shortTitle: "Tri Force Heroes",
      platform: "3DS",
      importance: "skip",
      statusDefault: "todo",
      waitBadge: false,
      blocked: false,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/d/db/The_Legend_of_Zelda_Tri_Force_Heroes_Boxart.jpg",
      alt: "Box art for Tri Force Heroes",
      versionNote: "Nintendo 3DS",
      why: "Skip. Co-op fashion romp — fun with friends, not needed for chronology or Switch path.",
      chronology: "Downfall-ish side story",
    },
    ph: {
      id: "ph",
      order: 28,
      title: "Phantom Hourglass",
      shortTitle: "PH",
      platform: "DS — no Switch",
      importance: "skip",
      statusDefault: "todo",
      waitBadge: false,
      blocked: true,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/5/5e/The_Legend_of_Zelda_Phantom_Hourglass_Game_Cover.jpg",
      alt: "Box art for Phantom Hourglass",
      versionNote: "Nintendo DS — no Switch release",
      why: "Skip for now (no Switch). Direct Wind Waker sequel — revisit if DS Classics or a remake appears.",
      chronology: "Adult timeline — after Wind Waker",
    },
    st: {
      id: "st",
      order: 29,
      title: "Spirit Tracks",
      shortTitle: "ST",
      platform: "DS — no Switch",
      importance: "skip",
      statusDefault: "todo",
      waitBadge: false,
      blocked: true,
      cover: null,
      alt: "Placeholder for Spirit Tracks",
      versionNote: "Nintendo DS — no Switch release",
      why: "Skip for now (no Switch). Train-and-phantom sequel to Phantom Hourglass on the Adult timeline.",
      chronology: "Adult timeline — after PH",
    },
    albw: {
      id: "albw",
      order: 30,
      title: "A Link Between Worlds",
      shortTitle: "ALBW",
      platform: "3DS only",
      importance: "recommended",
      statusDefault: "todo",
      waitBadge: false,
      blocked: true,
      cover:
        "https://upload.wikimedia.org/wikipedia/en/1/1b/The_Legend_of_Zelda_A_Link_Between_Worlds_NA_cover.jpg",
      alt: "Box art for A Link Between Worlds",
      versionNote: "Nintendo 3DS — no Switch port yet",
      why: "Recommended but 3DS-only. Brilliant wall-merge sequel spirit to ALttP. Play on 3DS/2DS if you have one.",
      chronology: "Downfall — after ALttP / Oracles",
    },
  },

  chronology: {
    intro:
      "Nintendo’s published chronology is a tree, not a single line. OoT is the split point.",
    trunk: [
      { id: "skyward", label: "Skyward Sword", note: "Origin" },
      { id: "minish", label: "The Minish Cap", note: "Force Era" },
      { id: "four-swords", label: "Four Swords", note: "Force Era" },
      { id: "oot", label: "Ocarina of Time", note: "The split" },
    ],
    branches: [
      {
        id: "downfall",
        title: "Downfall Timeline",
        color: "#c62828",
        games: [
          "ALttP",
          "Oracles",
          "Link’s Awakening",
          "ALBW",
          "Echoes of Wisdom",
          "Zelda I / II",
        ],
      },
      {
        id: "child",
        title: "Child Timeline",
        color: "#2e7d32",
        games: ["Majora’s Mask", "Twilight Princess", "Four Swords Adventures"],
      },
      {
        id: "adult",
        title: "Adult Timeline",
        color: "#1565c0",
        games: ["Wind Waker", "Phantom Hourglass", "Spirit Tracks"],
      },
    ],
    farFuture: [
      { id: "botw", label: "Breath of the Wild", note: "Far future" },
      { id: "totk", label: "Tears of the Kingdom", note: "Sequel" },
    ],
    whyNotPure:
      "This play order is not pure timeline order. It prioritizes what you can actually play on Switch → Switch 2, narrative payoffs (OoT before its sequels), and avoiding spoilers between connected pairs (BotW → TotK). Classics availability and remakes matter more than strict chronology for a living backlog.",
  },

  connections: [
    {
      id: "oot-majora",
      pair: ["Ocarina of Time", "Majora’s Mask"],
      relation: "Direct sequel (same Link, Child ending)",
      tip: "Finish OoT first — Majora assumes you know that Link.",
    },
    {
      id: "oot-ww",
      pair: ["Ocarina of Time", "The Wind Waker"],
      relation: "Adult-timeline consequence",
      tip: "Wind Waker’s flooded Hyrule answers OoT’s Adult ending.",
    },
    {
      id: "ww-ph-st",
      pair: ["Wind Waker", "PH / Spirit Tracks"],
      relation: "Adult-timeline sequels",
      tip: "Skip PH/ST for now (DS only); still know they continue WW’s world.",
    },
    {
      id: "alttp-albw",
      pair: ["A Link to the Past", "A Link Between Worlds"],
      relation: "Spiritual / world sequel",
      tip: "ALBW reuses ALttP’s map with wall-merge twists — 3DS only for now.",
    },
    {
      id: "oracles",
      pair: ["Oracle of Ages", "Oracle of Seasons"],
      relation: "Linked pair",
      tip: "Play both and link passwords for the full ending.",
    },
    {
      id: "botw-totk",
      pair: ["Breath of the Wild", "Tears of the Kingdom"],
      relation: "Direct continuous sequel",
      tip: "Play TotK immediately after BotW — do not sandwich other games between them.",
    },
    {
      id: "skyward-master",
      pair: ["Skyward Sword", "Master Sword saga"],
      relation: "Mythic origin",
      tip: "Skyward sets up Demise’s curse and the Master Sword’s birth.",
    },
  ],
};
